name: Convert Issue to Markdown

on:
  workflow_dispatch:
    inputs:
      title:
        description: "The title of the issue"
        required: true
        default: "Default Title"
      body:
        description: "The body of the issue"
        required: true
        default: "Default Body"

jobs:
  create-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate markdown & update JSON in a single step
        run: |
          echo "Converting issue to markdown..."

          # ====== 1) 폴더 생성 (없으면)
          if [ ! -d "public/posts" ]; then
            mkdir -p public/posts
          fi

          # ====== 2) 변수 설정
          ISSUE_TITLE="${{ github.event.inputs.title }}"
          ISSUE_BODY="${{ github.event.inputs.body }}"
          ISSUE_DATE=$(date +'%Y%m%d')
          ISSUE_COUNT=$(ls public/posts | grep "$ISSUE_DATE" | wc -l)
          FILE_NAME="public/posts/${ISSUE_DATE}_$((ISSUE_COUNT + 1)).md"

          # ====== 3) 마크다운 파일 생성
          echo "## $ISSUE_TITLE" > "$FILE_NAME"
          echo "" >> "$FILE_NAME"
          echo "$ISSUE_BODY" >> "$FILE_NAME"

          # ====== 4) posts.json 업데이트
          if [ ! -f public/posts.json ]; then
            echo "[]" > public/posts.json
          fi

          NEW_ID=$(($(jq length public/posts.json) + 1))
          ISSUE_DATE_FORMATTED="${ISSUE_DATE:0:4}-${ISSUE_DATE:4:2}-${ISSUE_DATE:6:2}"
          FIRST_LINE=$(echo "$ISSUE_BODY" | sed -n 1p)

          UPDATED_JSON=$(jq ". += [{
            \"id\": $NEW_ID,
            \"filename\": \"$(basename "$FILE_NAME")\",
            \"title\": \"$ISSUE_TITLE\",
            \"summary\": \"${FIRST_LINE}\",
            \"date\": \"$ISSUE_DATE_FORMATTED\"
          }]" public/posts.json)

          echo "$UPDATED_JSON" > public/posts.json

          # ====== 5) 변경사항 커밋 & 푸시
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/posts/*.md public/posts.json
          git commit -m "Add markdown file and update posts.json from issue"
          git push
