name: Convert Issue to Markdown

on:
  workflow_dispatch:
    inputs:
      title:
        description: "The title of the issue"
        required: true
        default: "Default Title"
      body:
        description: "The body of the issue"
        required: true
        default: "Default Body"

jobs:
  create-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert issue to Markdown
        run: |
          echo "Converting issue to markdown..."
          # 이슈에서 전달받은 제목 및 본문
          ISSUE_TITLE="${{ github.event.inputs.title }}"
          ISSUE_BODY="${{ github.event.inputs.body }}"

          # 날짜 및 기존 파일 개수 기반으로 파일명 생성
          ISSUE_DATE=$(date +'%Y%m%d')
          ISSUE_COUNT=$(ls public/posts | grep $ISSUE_DATE | wc -l)
          FILE_NAME="public/posts/${ISSUE_DATE}_$((ISSUE_COUNT + 1)).md"

          # 마크다운 파일 생성
          echo "## $ISSUE_TITLE" > $FILE_NAME
          echo "" >> $FILE_NAME
          echo "$ISSUE_BODY" >> $FILE_NAME

      - name: Commit and push Markdown file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/posts/*.md
          git commit -m "Add markdown file from issue"
          git push
