name: Restrict Issues

on:
  issues:
    types: [opened]

jobs:
  restrict-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue creator
        uses: actions/github-script@v6
        with:
          script: |
            const authorizedUser = process.env.AUTHORIZED_USER;
            const issueCreator = context.payload.issue.user.login;
            console.log(`Authorized User: ${authorizedUser}`);
            console.log(`Issue Creator: ${issueCreator}`);

            if (issueCreator !== authorizedUser) {
              console.log(`Unauthorized user: ${issueCreator}`);
              await github.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                state: 'closed',
                body: 'This issue has been closed because you are not authorized.'
              });
              return; // 작업 중단
            } else {
              console.log(`Authorized user: ${issueCreator}`);
            }
        env:
          AUTHORIZED_USER: ${{ secrets.AUTHORIZED_USER }}

      - name: Trigger Convert Issue Workflow
        if: ${{ success() }} # 작성자가 허가된 경우에만 실행
        shell: bash
        run: |
          echo "Triggering Convert Issue Workflow..."

          # 1) 이슈 제목/본문을 변수에 저장
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"

          # 2) 멀티라인을 안전한 JSON 문자열로 변환 (개행 이스케이프)
          SAFE_BODY=$(echo "${ISSUE_BODY}" | jq -Rs .)
          echo "Safe Body: $SAFE_BODY"

          # 3) JSON Payload 파일 생성
          cat <<EOF > dispatch.json
          {
            "ref": "main",
            "inputs": {
              "title": "${ISSUE_TITLE}",
              "body": ${SAFE_BODY}
            }
          }
          EOF

          # 4) Convert Issue to MD 워크플로우 호출
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            --data @dispatch.json \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/convert-issue-to-md.yml/dispatches
